CREATE TABLE Users
(
    userId VARCHAR(100) PRIMARY KEY,
    -- GENERATED BY THE SERVER
    email VARCHAR(100) UNIQUE NOT NULL,
    -- ENSURES THAT ALL VALUES IN A COLUMN ARE DIFFERENT
    -- Both the UNIQUE and PRIMARY KEY constraints provide a 
    -- guarantee for uniqueness for a column or set of columns
    emailSent VARCHAR(100),
    userPassword VARCHAR(255),
    firstName VARCHAR(100),
    lastName VARCHAR(100),
    streetAddress VARCHAR(100),
    city VARCHAR(100),
    country VARCHAR(100),
    phone VARCHAR(100),
    -- WILL BE CONVERTED TO STRING
    isDeleted INT DEFAULT 0,
	isAdmin INT DEFAULT 0
)